// Generated by gencpp from file action_primitive_variation/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ACTION_PRIMITIVE_VARIATION_MESSAGE_ADDTWOINTS_H
#define ACTION_PRIMITIVE_VARIATION_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <action_primitive_variation/AddTwoIntsRequest.h>
#include <action_primitive_variation/AddTwoIntsResponse.h>


namespace action_primitive_variation
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace action_primitive_variation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::action_primitive_variation::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::action_primitive_variation::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::action_primitive_variation::AddTwoInts > {
  static const char* value()
  {
    return "action_primitive_variation/AddTwoInts";
  }

  static const char* value(const ::action_primitive_variation::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::action_primitive_variation::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::action_primitive_variation::AddTwoInts > 
template<>
struct MD5Sum< ::action_primitive_variation::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::action_primitive_variation::AddTwoInts >::value();
  }
  static const char* value(const ::action_primitive_variation::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_primitive_variation::AddTwoIntsRequest> should match 
// service_traits::DataType< ::action_primitive_variation::AddTwoInts > 
template<>
struct DataType< ::action_primitive_variation::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::action_primitive_variation::AddTwoInts >::value();
  }
  static const char* value(const ::action_primitive_variation::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::action_primitive_variation::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::action_primitive_variation::AddTwoInts > 
template<>
struct MD5Sum< ::action_primitive_variation::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::action_primitive_variation::AddTwoInts >::value();
  }
  static const char* value(const ::action_primitive_variation::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_primitive_variation::AddTwoIntsResponse> should match 
// service_traits::DataType< ::action_primitive_variation::AddTwoInts > 
template<>
struct DataType< ::action_primitive_variation::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::action_primitive_variation::AddTwoInts >::value();
  }
  static const char* value(const ::action_primitive_variation::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_PRIMITIVE_VARIATION_MESSAGE_ADDTWOINTS_H
